version: 0.2

env:
  variables:
    PATH: "$HOME/.dotnet:$PATH"
    DOTNET_ROOT: "$HOME/.dotnet"

phases:
  install:
    commands:
      - echo "Installing the latest .NET 9.0 from the 9.0 channel"
      - wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
      - chmod +x dotnet-install.sh
      - ./dotnet-install.sh --channel 9.0 --install-dir "$HOME/.dotnet"
      - "$HOME/.dotnet/dotnet --version"  
  pre_build:
    commands:
      - echo "Restore phase"
      - "$HOME/.dotnet/dotnet restore"
  build:
    commands:
      - echo "Build phase"
      - "$HOME/.dotnet/dotnet build -c Release"
      - echo "Test phase"
      - "$HOME/.dotnet/dotnet test **/CarPriceApi.Tests.csproj --no-build"
  post_build:
    commands:
      - echo "Post build phase"
      - "$HOME/.dotnet/dotnet publish **/CarPriceApi.csproj -c Release -o ./publish --no-build"
artifacts:
  files:
    - '**/*'
  base-directory: './publish'