version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 9.0
    commands:    
      - echo "Current .NET version:"
      - dotnet --version
  pre_build:
    commands:
      - echo "Restore phase"
      - dotnet restore
  build:
    commands:
      - echo "Build phase"
      - dotnet build -c Release --no-restore
      - echo "Test phase"
      - dotnet test **/CarPriceApi.Tests.csproj --no-build
  post_build:
    commands:
      - echo "Post build phase"
      - dotnet publish **/CarPriceApi.csproj -c Release -o ./publish --no-build

artifacts:
  files:
    - '**/*'
  base-directory: './publish'