version: 0.2

phases:
  install:
    commands:
      - echo "Installing .NET SDK 9.0"
      - sudo add-apt-repository ppa:dotnet/backports
      - sudo apt-get update && \
          sudo apt-get install -y dotnet-sdk-9.0
      - echo "Install the runtime"
      - sudo apt-get update && \
          sudo apt-get install -y aspnetcore-runtime-9.0
      - echo "Verifying installed .NET version"
      - dotnet --version
  pre_build:  
    commands:
      - echo "Restore phase"
      - dotnet restore
  build:
    commands:
      - echo "Build phase"
      - dotnet build -c Release --no-restore
      - echo "Test phase"
      - dotnet test **/CarPriceApi.Tests.csproj --no-build
  post_build:
    commands:
      - echo "Post build phase"
      - dotnet publish -c Release -o ./publish --no-build

artifacts:
  files:
    - '**/*'
  base-directory: './publish'
