version: 0.2

phases:
  restore:
    commands:
      - echo "Restore phase"
      - dotnet restore
  build:
    commands:
      - echo "Build phase"
      - dotnet build -c Release --no-restore
  test: 
    commands:
      - echo "Test phase"
      - dotnet test **/CarPriceApi.Tests.csproj --no-build
  post_build:
    commands:
      - echo "Post build phase"
      - dotnet publish -c Release -o ./publish --no-build
artifacts:
  files:
    - '**/*'
  base-directory: './publish'