version: 0.2

phases:
  install:
    commands:
      - echo "Updating package repository"
      - apt-get update -y
      - echo "Setting up Microsoft package repository for .NET SDK"
      - wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
      - apt-get install -y ./packages-microsoft-prod.deb
      - apt-get update
      - echo "Installing .NET SDK 9.0"
      - apt-get install -y dotnet-sdk-9.0
      - echo "Verifying installed .NET version"
      - dotnet --version
  pre_build:
    commands:
      - echo "Restore phase"
      - dotnet restore
  build:
    commands:
      - echo "Build phase"
      - dotnet build -c Release --no-restore
      - echo "Test phase"
      - dotnet test **/CarPriceApi.Tests.csproj --no-build
  post_build:
    commands:
      - echo "Post build phase"
      - dotnet publish -c Release -o ./publish --no-build

artifacts:
  files:
    - '**/*'
  base-directory: './publish'
